### ISSUE TITLE
Possibility to cancel the whole transfer of mutliple samples in queue

### ISSUE THREAD

**Issue by snd1** [dagargo/elektroid#28] opened 2020-11-14 15:32 UTC
Atm it is only possible to abort the current process of one sample, but then its continuing with the next sample in the queue.
This is bad if you have 100+ samples in the queue...
There is no possibility to cancel the whole transfer of mutliple samples, only by closing the application itself, afaik.

**Comment by dagargo** [comment] 2020-11-14 17:10
You can not cancel all the tasks but you can remove all the queued tasks (not running yet) which results in the same behaviour. It's the second button right to the task queue.

Does this work for you?

**Comment by snd1** [comment] 2020-11-14 18:47
oops sorry, i don't know why i didn't try that button before... thanks :+1:

**Comment by snd1** [comment] 2020-12-01 18:09
I reopened the issue because canceling the whole transfer would be still a great option

**Comment by snd1** [comment] 2020-12-02 20:38
hm, some transfers doesn't stop at once, some do... i need to test this further, because when all can stop immediately then there is no need for this feature request.

**Comment by snd1** [comment] 2021-01-21 14:49
i close it again

**Comment by dagargo** [comment] 2021-01-21 18:48
I'm keeping this in mind.

I think the current implementation is confusing so it will be better to reopen this and discuss what to do at some point in the future but not in this release because it's taking too long.

For completeness' sake, this is how the current buttons work.

1. Cancel only the current active transfer.
2. Remove all tasks that are queued, so tasks completed or running will remain.
3. Remove all completed tasks, so queued tasks and the currently running task will remain.

It's true that in order to delete every task the user needs to click on the 3 buttons, which is cumbersome.

**Comment by dagargo** [comment] 2021-02-07 19:56
This should be reworked on the next release.

**Comment by dagargo** [comment] 2021-02-22 17:33
I'm proposing this solution with 3 buttons. It's not implemented yet.

* Cancel All Tasks button, which cancels not only the current transfer but any other transfer waiting in the queue.
* Remove Queued tasks, which removes all the tasks waiting. (Same functionality as in 1.3 version.)
* Clear Finished Tasks, which clears all the tasks that are completed but leaves the ones waiting. (Same functionality as in 1.3 version.)

What do you think about this?

**Comment by snd1** [comment] 2021-02-22 19:30
sounds good to me! :-)

**Comment by dagargo** [comment] 2021-06-20 15:57
It's been a long time but this issue has been finally implemented in 878c8da5c829787d90a71808217c31aceccc49ae. It would be nice if you could check it out too.

Also, @snd1  and  @trebmuh, a translation has changed. I include here this change and another one so you don't need to look for these. Let me know if everything is OK. TIA.

https://github.com/dagargo/elektroid/blob/878c8da5c829787d90a71808217c31aceccc49ae/po/de.po#L140-L143

https://github.com/dagargo/elektroid/blob/878c8da5c829787d90a71808217c31aceccc49ae/po/de.po#L238-L240

https://github.com/dagargo/elektroid/blob/878c8da5c829787d90a71808217c31aceccc49ae/po/fr.po#L140-L143

https://github.com/dagargo/elektroid/blob/878c8da5c829787d90a71808217c31aceccc49ae/po/fr.po#L242-L244

FYI, version 1.4 is about to be released.

**Comment by trebmuh** [comment] 2021-07-09 20:11
All good for those 2 French translations.
Have a nice release :+1:

**Comment by dagargo** [comment] 2021-07-18 11:49
This is included in the 1.4 version, which I've released just now.

I'm leaving this open just in case it's not perfect.

**Comment by dagargo** [comment] 2021-08-14 13:00
I'm closing this as solved.

If it is not working as intended, please, reopen.

**Closed by dagargo** 2021-08-14 13:00 UTC

**Comment by snd1** [comment] 2021-08-14 16:44
Sorry for the late reply, has been very busy weeks for me. Looks fine, Thanks a lot bro! :100:
