### ISSUE TITLE
elektroid doesn't react on Raspberry Pi B 3 with Raspbian Buster

### ISSUE THREAD

**Issue by yuncam** [dagargo/elektroid#13] opened 2020-04-21 19:57 UTC
![2020-04-21-214303_1920x1080_scrot](https://user-images.githubusercontent.com/39299339/79908148-06b91e00-841b-11ea-9817-a7cc969482c1.png)
![2020-04-21-214404_1920x1080_scrot](https://user-images.githubusercontent.com/39299339/79908161-0b7dd200-841b-11ea-8c63-c6b678c50b61.png)
![2020-04-21-214524_1920x1080_scrot](https://user-images.githubusercontent.com/39299339/79908165-0caeff00-841b-11ea-9209-9282e2464124.png)
![2020-04-21-214600_1920x1080_scrot](https://user-images.githubusercontent.com/39299339/79908169-0de02c00-841b-11ea-88f7-5392ee91ced8.png)

**Comment by dagargo** [comment] 2020-05-09 17:36
I managed to run the code on a Raspberry Pi and I replicated the error.

The reason for this freeze was that getopt returns an int and not a char, which is signed on i386/amd64 but unsigned in the armv6l so both applications were stuck in the following sentence because it was returning 255 instead of -1.
```
while ((c = getopt (argc, argv, "v")) != -1)
```
The bug is fixed in 9f2044042e9c24906f80d72e4e5c5c2bd9904a27.

For more information, take a look at https://www.raspberrypi.org/forums/viewtopic.php?t=33876.

**Comment by yuncam** [comment] 2020-05-09 20:00
elektroid app and elektroid-cli start up normally, but choosing and selecting my Digitakt in the dropdown menu doesn't work.

`elektroid-cli -v -v ld` returns: 
> Adding hw:1 (Elektron Digi...... 1 Elektron Digitakt MIDI 1

`elektroid-cli -v -v info 1` returns:
> Initializing connector to 'hw:1'...
> Setting blocking mode...
> Stopping device...
> Raw message sent: f0 00 20 3c 10 00 00 00 00 00 00 01 f7
> Message sent: 00 00 00 00 01
> Destroying connector...

`elektroid-cli -v -v ls 1:/` returns:
> Initializing connector to 'hw:1'...
> Setting blocking mode...
> Stopping device...
> Raw message sent: f0 00 20 3c 10 00 00 00 00 00 00 01 f7
> Message sent: 00 00 00 00 01
> Destroying connector...
> Raw message sent: f0 00 20 3c 10 00 00 00 01 00 00 10 2f 00 f7
> Message sent: 00 01 00 00 10 2f 00
> connector.c: Input port is NULL

**Comment by dagargo** [comment] 2020-05-10 12:13
Let's focus on the info command. This is what I get.
```
$ elektroid-cli -v -v info 1
Initializing connector to 'hw:1'...
Setting blocking mode...
Stopping device...
Raw message sent: f0 00 20 3c 10 00 00 00 00 00 00 01 f7
Message sent: 00 00 00 00 01
Raw message received: f0 00 20 3c 10 00 04 00 09 00 00 01 0c 10 00 01 02 10 13 11 12 20 00 21 22 23 30 31 32 40 00 41 42 44 69 67 69 74 00 61 6b 74 00 f7
Message received: 00 09 00 00 81 0c 10 01 02 10 13 11 12 20 21 22 23 30 31 32 40 41 42 44 69 67 69 74 61 6b 74 00
Raw message sent: f0 00 20 3c 10 00 00 00 01 00 00 02 f7
Message sent: 00 01 00 00 02
Raw message received: f0 00 20 3c 10 00 04 00 0a 00 01 02 30 30 00 33 32 00 31 2e 31 31 00 00 f7
Message received: 00 0a 00 01 82 30 30 33 32 00 31 2e 31 31 00
Connected to Digitakt 1.11
Digitakt 1.11
Destroying connector...
```

The problem is that you are not receiving any messages. After a quick look at the source code, it seems there are no errors like the previous one. I'll take a deeper look.

For the moment, colud you check these?
* Elektroid closes the connection after a 5 seconds timeout. Does it take 5 seconds before writing "Destroying connector..."?
* Is the configuration under Settings, MIDI config and Port config is properly set up?
* Have you tried the Elektron Transfer application with the same configuration?

**Comment by yuncam** [comment] 2020-05-10 12:56
- Yes, it does take several seconds before "Destroying connector..." message.

- Yes, I tried it with Elektron Transfer App and it works.

Digitakt Settings:
![image](https://user-images.githubusercontent.com/39299339/81499802-5ed29a00-92ce-11ea-92b0-1b7f7bbedbb4.jpeg)
![image](https://user-images.githubusercontent.com/39299339/81499806-65f9a800-92ce-11ea-9ba9-dcad785d4b12.jpeg)
![image](https://user-images.githubusercontent.com/39299339/81499807-6a25c580-92ce-11ea-8729-7ffe0f0a61ae.jpeg)

**Comment by yuncam** [comment] 2020-05-11 02:11
Tested with newest commit.(https://github.com/dagargo/elektroid/commit/a246bca1efedccfe13926ad9f938d7b464a2e18c)
![test](https://user-images.githubusercontent.com/39299339/81518178-79902780-933d-11ea-993a-9b6a73b7acd2.jpg)

**Comment by dagargo** [comment] 2020-05-11 18:22
The commit you mention was meant to fix something I noticed in one of your tests. `elektroid-cli` should end if the connection was not established and should not try to execute any command. So thank you both for pointing this out and for testing it.

Sadly, I'm out of ideas and I think I cannot advance more with this issue unless I get physical access to a Raspberry Pi.

**Comment by dagargo** [comment] 2020-11-14 19:11
I haven't got my hands on a Raspberry Pi yet but there have been a lot of improvements lately and perhaps this got fixed.

More specifically, in commit (a58d5b54c08bb5a045023d15e4981cab11f9f0d7) a bug prevented data to be properly read which led to exactly the same behaviour you were having. This happened only on quite old and slow computers so, perhaps, its related to your issue.

**Comment by dagargo** [comment] 2020-12-27 10:54
I can confirm that Elektroid is working nicely but very slowly on a Raspberry Pi Model B Rev 1.

Feel free to reopen the issue if you still have problems.

**Closed by dagargo** 2020-12-27 10:54 UTC
