### ISSUE TITLE
Audio preview of samples should happen in parallel (or before) showing the waveform?

### ISSUE THREAD

**Issue by simonvanderveldt** [dagargo/elektroid#23] opened 2020-08-24 18:48 UTC
When browsing local samples it seems like the waveform first needs to be calculated and shown before the sample is played/previewed.
This is especially noticeable on longer samples.
Is the waveform visualization something that could be calculated in the background whilst the preview is triggered immediately?
If that's not possible it might be an idea to trigger the audio preview first before calculating/showing the waveform visualization?

P.S. I also noticed something that sounds like a change in volume or possibly a short hiccup when playing back the audio previews. Have you noticed this as well?

**Comment by dagargo** [comment] 2020-08-26 09:16
Since 7afbb896758ed151a9e1d32b51b769310f0d33e7, audio starts playing before the sample is fully loaded.

Let me know if this works for you.

**Comment by dagargo** [comment] 2020-08-26 09:20
Regarding the changes in volume, it happens to me as well. I don't know what's going on but I suspect is something related to PulseAudio.

But, definitely, it should be an issue on its own.

**Comment by dagargo** [comment] 2020-08-26 19:20
I forgot to mention a couple of things.

Firstly, audio can only be played after loading the file, or at least after loading a small fragment of it. This is due to the fact that many audio formats are allowed, even compressed ones, so the loading process also transforms the file contents. Besides, transformation to mono and 48KHz is done too during the same process.

Secondly, it's possible that the size of given fragment is too small, which would lead to audio dropouts. It's set at 4800 samples. I think any reasonable modern computer should perform well under this constraint but we could increase it if we face any dropouts.

**Comment by dagargo** [comment] 2020-08-27 20:05
7afbb896758ed151a9e1d32b51b769310f0d33e7 introduced a regression bug.

Reported in #24 and fixed in 5fbfa816acd4e188d5b4c996a849ae76c6e250e9.

**Closed** 2020-10-31 10:09 UTC
