### ISSUE TITLE
Huge file transfers get irregular errors

### ISSUE THREAD

**Issue by snd1** [dagargo/elektroid#29] opened 2020-12-02 21:19 UTC
"Huge sample transfers" get into errors after a while.... somehow:

**test 1**
sample pack 1: 11th sample stops at 29% with Unexpected status
sample pack 2: 13th sample, stops at 87% with Unexpected status
sample pack 3: 1st sample, stops at 89% with Unexpected status

**test 2**
sample pack 1: 4th sample stops at 93% with Unexpected status
sample pack 2: 19th sample, stops at 83% with Unexpected status
sample pack 3: 33th sample, stops at 35% with Unexpected status

all sample packs are stereo samples in WAV format and 44100Hz
the order of the samples were with each test the same

sample files of pack 1 are around 5MB
sample files of pack 2 are between 100kb and 1MB
sample files of pack 3 are between 1,5MB and 5MB

i also i observed when one file stops with error, more errors will follow with next samples (but not all)

if you need more infos i'm happy to help

**Comment by dagargo** [comment] 2020-12-06 20:19
I've successfully uploaded 16 larger that 5 MB samples without any issues so I haven't managed to replicate the error. Despite this, I've found a few things that were not right regarding the task queue the default timeout value.

In particular, I've found that sometimes the timeout has to be bigger that 2 s because when preparing for big sample uploads it takes my Digitakt more than that time to answer. This was causing some freezes and has been addressed in 4f45cd215aed1240afd924496db8773f980db1d9 and e645bb0d331323df99c51e7489e0b95f9fb2cda7. Perhaps this could be related to this issue.

Anyway, I have some questions regarding this.

- What do you mean with "Unexpected status"? Is it that a task status is mark as "Undefined" in the task queue?
- Are this errors happening randomly? I mean, is the error appearing at the same sample and same percent for same set of samples if you repeat the test? I don't think this is related to the samples themselves but I would like to test them.

**Comment by dagargo** [comment] 2021-01-05 16:47
After lots of testing I can say I have not reproduced this error anymore.

However, I have hopefully protected all shared variables to avoid running conditions, even in some cases are not needed now since both reader and writer are inside the main `gtk` loop.

Besides, I have tried `elektroid` in very old hardware and I have got some apparently freezes but after letting it continue for some time it recovers from such a state.

Let me know if you keep having the errors.

**Comment by snd1** [comment] 2021-01-11 19:17
I will give an update in this week, I will test it also on other devices.

**Comment by dagargo** [comment] 2021-01-11 21:44
Whenever you manage to test it, run it in verbose mode with `elektroid -v`. In case something goes wrong, it might help us to debug.

Thanks for offering to test this again.

**Comment by snd1** [comment] 2021-01-21 14:41
sorry for the late reply, i tested on 2 devices and only on my dell optiplex 9010 i have files that aren't transferred or only partial transferred.

the output from -v option doesn't tell me anything, i don't know if it will help you (this is only the part where some transfers failed, but for i don't see any difference):

`DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 3c 11 6f 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 bc 11 ef c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 71 00 00 42 00 01 40 60 00 00 00 20 00 00 2e 0d 40 00 6e 59 73 53 58 78 6d 7d 59 03 47 08 10 47 0c 24 10 0f 12 4d 02 13 5a 13 14 11 19 0f 14 0b 0b 1a 07 1c 03 53 55 7f...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f1 00 00 42 00 01 e0 00 00 00 20 00 00 0d c0 00 ee d9 f3 53 f8 6d fd d9 03 47 08 47 0c a4 10 0f 12 4d 13 5a 13 14 11 99 0f 0b 0b 9a 07 9c 03 53 ff 26 fb 60 f8 59 f6 56 f5 82 f6 09 f7 d5 fa...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 3d 11 70 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 bd 11 f0 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 72 00 00 42 00 01 40 60 00 00 00 20 00 00 2e 0d 60 00 6e 64 6a 50 57 66 51 63 17 60 33 5f 3b 4c 5e 55 5f 58 60 47 7f 62 71 65 22 68 11 6b 6a 00 6e 31 70 70 72 09 75 72...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f2 00 00 42 00 01 e0 00 00 00 20 00 00 0d e0 00 ee e4 ea 50 e6 51 e3 17 e0 b3 df 4c de d5 df 58 e0 c7 e2 f1 e5 a2 e8 91 eb 80 ee 31 f0 70 f2 09 f2 eb f3 06 f2 76 f1 6f ef f8 ee 58 ec bc eb...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 3e 11 71 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 be 11 f1 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 73 00 00 42 00 01 40 60 00 00 00 20 00 00 0e 0e 00 00 79 7b 7c 03 48 7e 4e 00 37 03 27 05 11 6f 07 04 09 4e 0a 45 2a 0b 74 0c 52 0d 01 0d 44 7b 0e 5a 0e 32 0f 04 02 0f...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f3 00 00 42 00 01 e0 00 00 00 20 00 00 0e 00 00 f9 fb fc 03 fe 4e 00 b7 03 27 05 6f 07 84 09 4e 0a c5 0b f4 0c d2 0d 81 0d fb 0e 5a 0e b2 0f 04 0f 75 10 0a 10 d3 11 d8 13 1f 14 9e 16 55 18...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 3f 11 72 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 bf 11 f2 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 74 00 00 42 00 01 40 60 00 00 00 20 00 00 0f 0e 20 00 6c 37 6c 6e 57 6d 2d 6d 6f 6d 43 6e 3b 23 6e 15 6f 12 6f 2e 55 70 5e 71 2c 72 1f 73 2f 25 74 55 75 19 76 7b 5d 78...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f4 00 00 42 00 01 e0 00 00 00 20 00 00 0e 20 00 ec b7 ec ee ed 2d ed 6f ed c3 ee 23 ee 95 ef 12 ef ae f0 5e f1 2c f2 1f f3 25 f4 55 f5 99 f6 fb f8 72 f9 ef fb 7f fd 04 fe 93 00 14 01 87 02...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 40 11 73 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c0 11 f3 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 75 00 00 42 00 01 40 60 00 00 00 20 00 00 05 0e 40 00 09 4f 0a 07 0a 0b 3e 0b 72 0c 22 0d 14 4d 0d 74 0e 1b 0f 37 22 0f 50 10 60 10 64 11 10 61 11 49 12 27 12 72 2a 12...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f5 00 00 42 00 01 e0 00 00 00 20 00 00 0e 40 00 09 cf 0a 87 0b 3e 0b f2 0c a2 0d 4d 0d f4 0e 9b 0f 37 0f d0 10 60 10 e4 11 61 11 c9 12 27 12 72 12 a7 12 cd 12 db 12 d3 12 b5 12 84 12 39 11...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 41 11 74 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c1 11 f4 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 76 00 00 42 00 01 40 60 00 00 00 20 00 00 0a 0e 60 00 7f 3d 7f 13 5d 7e 40 7c 22 7a 3d 77 2e 16 73 43 6e 6c 6a 30 5d 65 6a 60 40 5c 7e 58 6b 66 56 15 54 54 53 21 57 54...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f6 00 00 42 00 01 e0 00 00 00 20 00 00 0e 60 00 ff 3d ff 13 fe 40 fc a2 fa 3d f7 16 f3 43 ee ec ea 30 e5 6a e0 c0 dc 7e d8 e6 d6 15 d4 54 d3 a1 d4 02 d5 65 d7 a1 da 85 dd d5 e1 57 e4 ba e7...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 42 11 75 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c2 11 f5 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 77 00 00 42 00 01 40 60 00 00 00 20 00 00 25 0e 00 00 05 03 05 49 28 05 1b 04 7d 04 10 02 4e 46 01 53 7f 49 7e 42 7f 7c 68 7b 36 7a 54 7a 2b 45 7a 0f 7a 38 7a 20 55 7b...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f7 00 00 42 00 01 e0 00 00 00 20 00 00 0e 80 00 05 83 05 c9 05 9b 04 fd 04 10 02 c6 01 53 ff c9 fe 42 fc e8 fb b6 fa d4 fa 45 fa 0f fa 38 fa a0 fb 55 fc 36 fd 29 fe 2c ff 0f ff d1 00 52 00...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 43 11 76 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c3 11 f6 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 78 00 00 42 00 01 40 60 00 00 00 20 00 00 2a 0e 20 00 77 19 78 26 5f 79 19 79 71 7a 2e 7b 3a 42 7b 36 7c 08 7c 3a 55 7c 4f 7c 50 7c 43 7c 2a 32 7c 28 7c 29 7c 44 5d 7c...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f8 00 00 42 00 01 e0 00 00 00 20 00 00 0e a0 00 f7 19 f8 26 f9 19 f9 f1 fa ae fb 42 fb b6 fc 08 fc 3a fc 4f fc 50 fc 43 fc 32 fc 28 fc 29 fc 44 fc 7e fc e3 fd 74 fe 3a ff 2c 00 51 01 a0 03...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 44 11 77 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c4 11 f7 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 20 11 79 00 00 42 00 01 40 60 00 00 00 20 00 00 2b 0e 40 00 79 13 79 0b 5d 7a 08 7a 0c 7b 20 7b 6a 41 7c 78 7d 44 7e 22 40 7f 17 00 14 01 1f 02 01 25 03 25 04 14 04 6a 22 05...
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f9 00 00 42 00 01 e0 00 00 00 20 00 00 0e c0 00 f9 13 f9 8b fa 08 fa 8c fb 20 fb c1 fc 78 fd 44 fe 22 ff 17 00 14 01 1f 02 25 03 25 04 14 04 ea 05 a5 06 36 06 a3 06 e1 06 f3 06 db 06 95 06...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 45 11 78 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c5 11 f8 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (6013): f0 00 20 3c 10 00 20 11 7a 00 00 42 00 01 40 60 00 00 00 14 76 00 2a 0e 60 00 7d 3a 7d 0f 77 7c 46 7c 5f 7b 52 7b 2f 2b 7a 65 79 07 78 1c 7f 77 22 76 27 75 29 74 7a 37 73 5c 73 11 72 6a 7d 71...
DEBUG:connector.c:509:(connector_tx): Message sent (5255): 11 fa 00 00 42 00 01 e0 00 00 00 14 76 00 0e e0 00 fd 3a fd 0f fc c6 fc 5f fb d2 fb 2b fa 65 f9 87 f8 9c f7 a2 f6 a7 f5 a9 f4 b7 f3 dc f3 11 f2 6a f1 e5 f1 84 f1 50 f1 43 f1 63 f1 ae f2 1e f2...
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 46 11 79 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c6 11 f9 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
DEBUG:connector.c:505:(connector_tx): Raw message sent (22): f0 00 20 3c 10 00 20 11 7b 00 00 41 00 01 44 60 00 00 0e 74 76 f7
DEBUG:connector.c:509:(connector_tx): Message sent (13): 11 fb 00 00 41 00 01 e0 00 00 0e f4 76
DEBUG:connector.c:804:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 6c 11 47 11 7a 42 00 00 00 00 00 00 f7
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c7 11 fa c2 00 00 00 00 00
ERROR:connector.c:1085:(connector_upload): Unexpected status
`
so i wonder, if the optiplex has maybe a general usb problem, because i tried different usb ports...

so if we can not reproduce it on any other device i think we can close this bug.

**Comment by dagargo** [comment] 2021-01-21 20:08
First of all, thank you for taking the time to test this on several devices. It takes time and it's not a very rewarding job, so no apologies needed. :+1: 

Looks like in both errors, a safety check is failing.

https://github.com/dagargo/elektroid/blob/9217f6cd3ccb14875cde93e2542772c4158d5c38/src/connector.c#L1056-L1059

https://github.com/dagargo/elektroid/blob/9217f6cd3ccb14875cde93e2542772c4158d5c38/src/connector.c#L1083-L1086

But what is really weird is that in every case you've included the received message is not the expected paired message based on the message ID.

Every sent message has the following structure:

* 2 bytes for the host (computer) message ID.
* 2 `0` bytes.
* 1 byte for the operation code.
* Data bytes.

Every received message has the following structure:
* 2 bytes for the device message ID.
* 2 bytes for the host (computer) message ID. The value is the same ID that was sent as the host message ID in the sent message.
* 1 byte for the operation code (same that was sent as the operation code in the sent message plus `0x80`.
* Data bytes. In some cases, the first data byte is the operation result.

This is one of the failures you've included (I'm only showing the non raw messages). Notice the sent ID `11 f8` but the replied ID `11 f7`.
```
DEBUG:connector.c:509:(connector_tx): Message sent (8209): 11 f8 00 00 42 00 01 e0 00 00 00 20 00 00 0e a0 00 f7 19 f8 26 f9 19 f9 f1 fa ae fb 42 fb b6 fc 08 fc 3a fc 4f fc 50 fc 43 fc 32 fc 28 fc 29 fc 44 fc 7e fc e3 fd 74 fe 3a ff 2c 00 51 01 a0 03...
DEBUG:connector.c:811:(connector_rx): Message received (10): 91 c4 11 f7 c2 00 00 00 00 00
ERROR:connector.c:1058:(connector_upload): Unexpected status
```

This needs to be investigated further but at first glance this is what's happening:

* At some point, a message is not received because of a timeout in Elektroid. Here, the application does not end and assumes the message is lost so it cancels the current pair request-response.
* But Elektroid continues with the next request-response and the reply to the previous message is received at this point.
* From now on, no pair of request-response will match.

There are two options here:
* The problem is in the timeout itself, which I would consider unlikely since 5 seconds must be enough. Also, I'd be really strange that only one single message is skipped but it's already there at the very next moment.
* The problem is that the message is not in the read buffer at the moment but it has already been received or the polling mechanism has not been notified that more data is available. This is why this line is needed and perhaps this should be reworked.

https://github.com/dagargo/elektroid/blob/9217f6cd3ccb14875cde93e2542772c4158d5c38/src/connector.c#L827

But I need to think about this.

**Comment by dagargo** [comment] 2021-01-23 17:52
The problem might be in the value returned here.

https://github.com/dagargo/elektroid/blob/9217f6cd3ccb14875cde93e2542772c4158d5c38/src/connector.c#L616

If the value is an error and is not `-EAGAIN`, the function `connector_rx_raw` would exit while the device is sending data or is not yet in the buffer. This would happen with an "Error while receiving message" error message. Could you check this out?

On the other hand there is a small bug that might be playing a role here.

https://github.com/dagargo/elektroid/blob/9217f6cd3ccb14875cde93e2542772c4158d5c38/src/connector.c#L608-L614

This block should always return to the polling and never try a read operation later since there is no data ready. Perhaps this is why you're getting the error. This has been fixed in 156ddeb48a4e00b0e4d01ada2cee6473147f2232.

Let me know if this fixes anything for you. If not, please include the first error line in the trace.

And thanks again for testing this.

**Comment by snd1** [comment] 2021-01-25 21:16
I am happy to help :-) Still got some errors:

   DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 00 75 70 00 00 42 00 00 00 0a 01 00 00 20 00 00 20 14 60 00 0a 52 09 5e 0a 08 66 07 04 06 2f 05 44 64 05 54 04 5b 04 77 08 04 17 03 37 03 7b 03 05 55 03 60 03 15 03 5b 08 04...
   DEBUG:connector.c:509:(connector_tx): Message sent (8209): 75 70 00 00 42 00 00 0a 01 00 00 20 00 00 14 e0 00 0a 52 09 5e 08 66 07 84 06 af 05 e4 05 54 04 db 04 77 04 17 03 b7 03 7b 03 55 03 60 03 95 03 db 04 3b 04 af 05 50 06 2c 07 1a 07 f9 08 bd 09...
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 22 75 6f 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 22 75 6f c2 00 00 00 00 00
   ERROR:connector.c:1062:(connector_upload): Unexpected status
   DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 00 75 71 00 00 42 00 00 00 0a 01 00 00 20 00 00 05 15 00 00 08 43 07 5b 08 07 2b 06 2c 06 54 05 50 71 05 06 05 41 05 35 08 05 1a 04 4c 04 77 04 11 30 03 5a 03 56 02 64 22 02...
   DEBUG:connector.c:509:(connector_tx): Message sent (8209): 75 71 00 00 42 00 00 0a 01 00 00 20 00 00 15 00 00 08 c3 07 db 07 2b 06 ac 06 54 05 f1 05 86 05 41 05 35 05 1a 04 cc 04 77 04 30 03 da 03 56 02 e4 02 9f 02 44 01 a3 00 fd 00 96 00 4f ff f7 ff...
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 23 75 70 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 23 75 70 c2 00 00 00 00 00
   ERROR:connector.c:1062:(connector_upload): Unexpected status
   DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 00 75 72 00 00 42 00 00 00 0a 01 00 00 20 00 00 01 15 20 00 0a 03 09 4c 20 09 19 09 60 09 25 08 54 71 08 45 08 1c 08 7a 00 08 5c 08 48 08 54 08 15 6d 08 18 08 50 08 7b 00 09...
   DEBUG:connector.c:509:(connector_tx): Message sent (8209): 75 72 00 00 42 00 00 0a 01 00 00 20 00 00 15 20 00 0a 03 09 cc 09 99 09 60 09 25 08 f1 08 c5 08 9c 08 7a 08 5c 08 48 08 54 08 6d 08 98 08 d0 08 fb 09 1c 09 24 09 2b 09 2c 09 20 09 0e 08 fa 08...
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 24 75 71 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 24 75 71 c2 00 00 00 00 00
   ERROR:connector.c:1062:(connector_upload): Unexpected status
   DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 00 75 73 00 00 42 00 00 00 0a 01 00 00 20 00 00 0a 15 40 00 7b 25 7b 11 55 7b 0d 7b 33 7b 62 7b 6e 29 7c 2c 7c 48 7d 7b 50 7e 3a 7f 1d 00 20 01 00 2f 02 39 03 4a 04 67 00 05...
   DEBUG:connector.c:509:(connector_tx): Message sent (8209): 75 73 00 00 42 00 00 0a 01 00 00 20 00 00 15 40 00 fb 25 fb 11 fb 0d fb 33 fb 62 fb a9 fc 2c fc c8 fd 7b fe 3a ff 1d 00 20 01 2f 02 39 03 4a 04 67 05 5d 06 52 07 30 07 fb 08 b7 09 4b 09 de 0a...
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 25 75 72 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 25 75 72 c2 00 00 00 00 00
   ERROR:connector.c:1062:(connector_upload): Unexpected status
   DEBUG:connector.c:505:(connector_tx): Raw message sent (9389): f0 00 20 3c 10 00 00 75 74 00 00 42 00 00 00 0a 01 00 00 20 00 00 0f 15 60 00 7e 07 7e 11 7f 7e 18 7e 1f 7e 30 7e 7f 37 7e 43 7e 4a 7e 51 7f 7e 58 7e 5c 7e 69 7e 7f 6b 7e 72 7e 7c 7e 7e 55 7f...
   DEBUG:connector.c:509:(connector_tx): Message sent (8209): 75 74 00 00 42 00 00 0a 01 00 00 20 00 00 15 60 00 fe 87 fe 91 fe 98 fe 9f fe b0 fe b7 fe c3 fe ca fe d1 fe d8 fe dc fe e9 fe eb fe f2 fe fc fe fe ff 08 ff 0f ff 14 ff 1a ff 20 ff 1c ff 1e ff...
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 26 75 73 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 26 75 73 c2 00 00 00 00 00
   ERROR:connector.c:1062:(connector_upload): Unexpected status
   DEBUG:connector.c:505:(connector_tx): Raw message sent (8841): f0 00 20 3c 10 00 00 75 75 00 00 42 00 00 00 0a 01 00 00 1e 20 00 2f 15 00 00 7f 69 7f 71 79 7f 71 7f 76 00 00 7f 7f 7d 7f 7c 7f 78 7f 79 78 7f 7d 7f 7a 00 0b 00 00 0c 00 0a 00 11 00 13 00 00...
   DEBUG:connector.c:509:(connector_tx): Message sent (7729): 75 75 00 00 42 00 00 0a 01 00 00 1e 20 00 15 80 00 ff e9 ff f1 ff f1 ff f6 00 00 ff fd ff fc ff f8 ff f9 ff fd ff fa 00 0b 00 0c 00 0a 00 11 00 13 00 19 00 13 00 14 00 0e 00 0e 00 10 00 08 00...
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 27 75 74 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 27 75 74 c2 00 00 00 00 00
   ERROR:connector.c:1062:(connector_upload): Unexpected status
   DEBUG:connector.c:505:(connector_tx): Raw message sent (22): f0 00 20 3c 10 00 00 75 76 00 00 41 00 00 04 0a 01 00 15 1e 20 f7
   DEBUG:connector.c:509:(connector_tx): Message sent (13): 75 76 00 00 41 00 00 0a 01 00 15 9e 20
   DEBUG:connector.c:808:(connector_rx): Raw message received (19): f0 00 20 3c 10 00 44 68 28 75 75 42 00 00 00 00 00 00 f7
   DEBUG:connector.c:815:(connector_rx): Message received (10): e8 28 75 75 c2 00 00 00 00 00
ERROR:connector.c:1089:(connector_upload): Unexpected status

**Comment by dagargo** [comment] 2021-02-07 19:54
After a lot of testing performed by @snd1 and me, looks like the problem was on the devices because under heavy load they were more prone to failures.

In the end, a 50 ms delay is used in the messaging loops when uploading, downloading and upgrading the OS. It's possible that this delay is too much but we'll use this for now and perhaps lower it or make it user configurable in the future.

**Closed by dagargo** 2021-02-07 19:54 UTC
